language: php
php:
  - '7.1'

install:
  - composer self-update
  - make install

script: make lint test_coverage

env:
  global:
    - CC_TEST_REPORTER_ID=9e6246672a75618fd7ec0b02eb06787579265a2854633443d8b6474a7dc624fa

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

